default: &default
  adapter: mysql2
  username: root
  password: mango

development:
  <<: *default
  database: quiniela_dev

test:
  <<: *default
  database: quiniela_test

production:
  <<: *default
  database: quiniela
